### ISSUE TITLE
Solicita datos

### ISSUE THREAD

**Issue by DrJoseGallardo** [Osaitus/TareaR#1]
Estimado Javier,

Podrias subir los datos al repositorio para poder verlos antes de la clase. Si no logras hacerlo, enviamelos por mail.

Saludos

**Comment by Osaitus** [comment]
Perdón, no conteste pero los archivos ya están subidos

**Comment by DrJoseGallardo** [comment]
Excelente, lo revisaré.

**Comment by Osaitus** [comment]
Hable con mi jefa e hicimos algunos cambios a lo que haríamos, ahora voy a trabajar directo con péptidos que los voy a obtener desde la digestión de un set de secuencias y a esos péptidos les voy a medir distintas propiedades, así que tengo que hacer esa tabla primero y después la cambio por la que esta en el repositorio, el trabajo no cambia, solo sobre que lo haría, solo informo por si se extraña por el cambio de tablas
